const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  mode: "jit",
  important: true,
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./ui/**/*.{js,ts,jsx,tsx}",
  ],
  purge: {
    options: {
      safelist: [
        "text-gray-600",
        "text-red-600",
        "text-orange-600",
        "text-amber-600",
        "text-yellow-600",
        "text-lime-600",
        "text-green-600",
        "text-emerald-600",
        "text-teal-600",
        "text-cyan-600",
        "text-sky-600",
        "text-blue-600",
        "text-indigo-600",
        "text-violet-600",
        "text-purple-600",
        "text-fuchsia-600",
        "text-pink-600",
        "text-rose-600",
        "dark:text-gray-200",
        "dark:text-red-200",
        "dark:text-orange-200",
        "dark:text-amber-200",
        "dark:text-yellow-200",
        "dark:text-lime-200",
        "dark:text-green-200",
        "dark:text-emerald-200",
        "dark:text-teal-200",
        "dark:text-cyan-200",
        "dark:text-sky-200",
        "dark:text-blue-200",
        "dark:text-indigo-200",
        "dark:text-violet-200",
        "dark:text-purple-200",
        "dark:text-fuchsia-200",
        "dark:text-pink-200",
        "dark:text-rose-200",
        "dark:bg-gray-800",
        "dark:bg-red-800",
        "dark:bg-orange-800",
        "dark:bg-amber-800",
        "dark:bg-yellow-800",
        "dark:bg-lime-800",
        "dark:bg-green-800",
        "dark:bg-emerald-800",
        "dark:bg-teal-800",
        "dark:bg-cyan-800",
        "dark:bg-sky-800",
        "dark:bg-blue-800",
        "dark:bg-indigo-800",
        "dark:bg-violet-800",
        "dark:bg-purple-800",
        "dark:bg-fuchsia-800",
        "dark:bg-pink-800",
        "dark:bg-rose-800",
        "bg-gray-50",
        "bg-red-50",
        "bg-orange-50",
        "bg-amber-50",
        "bg-yellow-50",
        "bg-lime-50",
        "bg-green-50",
        "bg-emerald-50",
        "bg-teal-50",
        "bg-cyan-50",
        "bg-sky-50",
        "bg-blue-50",
        "bg-indigo-50",
        "bg-violet-50",
        "bg-purple-50",
        "bg-fuchsia-50",
        "bg-pink-50",
        "bg-rose-50",
      ],
    },
  },
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter var", ...defaultTheme.fontFamily.sans],
        brand: "Antipasto Pro",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
