import {
  BehaviourResponse,
  HomeworksResponse,
  BadgesResponse,
  ActivityResponse,
} from "classcharts-api/dist/types";
import ClassCharts from "types/ClassCharts";

export const studentInfo = {
  allow_pupils_add_timetable_notes: false,
  announcements_count: 0,
  avatar_url:
    "https://195ec04504ea0272771e-7c2c6dacbab7a2b2d574b53c70c1fe31.ssl.cf3.rackcdn.com/23.2.0/img/faces/default.png",
  survey_id: 0,
  can_upload_attachments: "no",
  detention_alias_plural_uc: "Detentions",
  display_absences: false,
  display_activity: true,
  display_announcements: true,
  display_attendance: false,
  display_attendance_percentage: true,
  display_attendance_type: "none",
  display_avatars: false,
  display_behaviour: true,
  display_classes: false,
  display_concern_submission: false,
  display_custom_fields: false,
  display_detentions: true,
  display_event_badges: true,
  display_homework: true,
  display_mental_health: false,
  display_mental_health_no_tracker: false,
  display_parent_behaviour: false,
  display_report_cards: false,
  display_rewards: false,
  display_timetable: true,
  display_two_way_communications: true,
  first_name: "Louis",
  has_birthday: true,
  has_new_survey: false,
  id: 6031766,
  is_disabled: false,
  last_name: "Kevan",
  messages_count: 0,
  name: "Louis Kevan",
  pupil_concerns_help_text: "",
  pusher_channel_name:
    "Pupil_fa635849867ff54d4d40e5b85e6ebc8951597e85c6105e385b9c58330a3f0fd0",
};

export const lessonsInfo = [
  {
    teacher_name: "Mr E Payne",
    lesson_id: 3899868,
    lesson_name: "9/Mu1",
    subject_name: "Music",
    is_alternative_lesson: false,
    period_name: "21TH:P1",
    period_number: "P1",
    room_name: "L4",
    date: "2022-03-03",
    start_time: "2022-03-03T08:45:00+00:00",
    end_time: "2022-03-03T09:45:00+00:00",
    key: 148753440,
    note_abstract: "",
    note: "",
    pupil_note_abstract: "",
    pupil_note: "",
    pupil_note_raw: "",
  },
  {
    teacher_name: "Mrs M Sanders",
    lesson_id: 3899928,
    lesson_name: "9A/Pe",
    subject_name: "Physical Education",
    is_alternative_lesson: false,
    period_name: "21TH:P2",
    period_number: "P2",
    room_name: "SP",
    date: "2022-03-03",
    start_time: "2022-03-03T09:45:00+00:00",
    end_time: "2022-03-03T10:45:00+00:00",
    key: 227719265,
    note_abstract: "",
    note: "",
    pupil_note_abstract: "",
    pupil_note: "",
    pupil_note_raw: "",
  },
  {
    teacher_name: "Mrs E Mellor",
    lesson_id: 3742306,
    lesson_name: "TuK3/Tu",
    subject_name: "TUTOR",
    is_alternative_lesson: false,
    period_name: "21TH:Tut",
    period_number: "Tut",
    room_name: "K6",
    date: "2022-03-03",
    start_time: "2022-03-03T10:45:00+00:00",
    end_time: "2022-03-03T11:05:00+00:00",
    key: 148754403,
    note_abstract: "",
    note: "",
    pupil_note_abstract: "",
    pupil_note: "",
    pupil_note_raw: "",
  },
  {
    teacher_name: "Mrs A Field",
    lesson_id: 3899817,
    lesson_name: "9/Gg1",
    subject_name: "Geography",
    is_alternative_lesson: false,
    period_name: "21TH:P3",
    period_number: "P3",
    room_name: "P15",
    date: "2022-03-03",
    start_time: "2022-03-03T11:20:00+00:00",
    end_time: "2022-03-03T12:20:00+00:00",
    key: 148755579,
    note_abstract: "",
    note: "",
    pupil_note_abstract: "",
    pupil_note: "",
    pupil_note_raw: "",
  },
  {
    teacher_name: "Miss O Davey",
    lesson_id: 3899933,
    lesson_name: "9A/Sc",
    subject_name: "Science",
    is_alternative_lesson: false,
    period_name: "21TH:P4",
    period_number: "P4",
    room_name: "P4",
    date: "2022-03-03",
    start_time: "2022-03-03T13:05:00+00:00",
    end_time: "2022-03-03T14:05:00+00:00",
    key: 148756059,
    note_abstract: "",
    note: "",
    pupil_note_abstract: "",
    pupil_note: "",
    pupil_note_raw: "",
  },
  {
    teacher_name: "Miss P Reed",
    lesson_id: 3899900,
    lesson_name: "9/Sp1",
    subject_name: "Spanish",
    is_alternative_lesson: false,
    period_name: "21TH:P5",
    period_number: "P5",
    room_name: "K11",
    date: "2022-03-03",
    start_time: "2022-03-03T14:05:00+00:00",
    end_time: "2022-03-03T15:05:00+00:00",
    key: 148756900,
    note_abstract: "",
    note: "",
    pupil_note_abstract: "",
    pupil_note: "",
    pupil_note_raw: "",
  },
];

export const homeworkInfo: HomeworksResponse = [
  {
    lesson: "9/Sp1",
    subject: "Spanish",
    teacher: "Miss P Reed",
    homework_type: "Homework",
    id: 10191283,
    title: "Spanish Holiday Hmwk",
    meta_title: "",
    description:
      "Please learn the vocab linked below. If you cannot see it, email me: redacted@school.comThere will be a mini test on this in the first week back!",
    issue_date: "2022-02-08",
    due_date: "2022-02-24",
    completion_time_unit: "minutes",
    completion_time_value: "",
    publish_time: "00:00:00",
    status: {
      id: 233808510,
      state: null,
      mark: null,
      mark_relative: 0,
      ticked: "no",
      allow_attachments: "no",
      first_seen_date: "2022-02-09T09:56:46+00:00",
      last_seen_date: "2022-02-09T09:56:46+00:00",
      attachments: [],
      has_feedback: false,
    },
    validated_links: [],
    validated_attachments: [
      {
        id: 7743328,
        file_name: "Yr 7 Ropa.PNG",
        file: 'https://attachments.classcharts.com/h/186461/ba5110ccdaca332819a194ed62bb88fb_20220208_093911.PNG?GoogleAccessId=attachments-classcharts%40edukey-classcharts.iam.gserviceaccount.com&Expires=1646356881&Signature=jp6l4BbCU5LsqecFbSgkOOo%2F%2BY2N2zN%2FU7It4r3nfmnADY6nWz3zDsNaGvw2XS2EBQ1VoKsav%2FmKlGy5vzlMGg%2Frg3aH1RmwI9Hr%2BpO8Ax5UJJDSD97BiwyH68S3A9WU0n%2FO6ZVfH43B4nWvGfIlOWJTx7UyEyOVVKou%2FrMyjUMoHc6zF7gaaNhi2aAi5pMrj%2B%2B6Ojdpt00wBRR3TQ06tB7ahAciTkMqCl4vGiA8n5LNMP9pjygAwl%2BIt7i6iGfSSt24Ra6Mda35htThi2%2FQsMvUN0QMFoULWWFEQQZfyoMYO7DC1LyCheV%2FWNMzBRjgjMMpmqjxGOjJPWlWHnFQog%3D%3D&response-content-disposition=attachment; filename="Yr+7+Ropa.PNG"',
        validated_file:
          "https://www.classcharts.com/redirect?url=ZGE2NDdiZTZiMTFkMjc5OWRmNDFlZGIzOTk3YWVhN2E2NmQzNmQ2YWI3NDcxNzM5NjVkYzJjMGJjMmFjYmQyOOduEeqHfJwLuumUi88ORyYT4jbMM%2B5u02AIIZ99ZoudHDIvOduFPkRY6WI02RM9lK6GLpHNClCfOkb0W2tEZKUpu5VX3PYQHcBxgRGTChVvMfr6hGeLtSKcVSsbBkWzzDk0hS2avOR3yRpQxHTHvRVryfpLsGoK9zW%2B1LQKeXUwsqgyklh83fGU2T%2Bt%2BBqOoPbDh5i9BroWGTC44s2EJc3%2B8gPrD%2FF%2F%2BBLePNLLdiYg%2BFjcz0Zwy802eeKQavLvIY5qdQQNFKJWqpZZFiW1Qley3rTk3THcGoc81AB7FRrVhLsRoEUY5FRLCjjogMada8z24qc4CuMbvTu0UpAdupAYdFCl%2Fh3DEfcbntiK6qPSy%2FGUgMbRQrTSwBerXa2dvHALQOjWNNXcyv6Vq8VxfMwVn83fK2xaYqL0qbqGc6GBewq2h4VT875MrGAApj%2FRAo7JhA%2FWaRmazRW%2BG4LKG5s3i2gvs7VfkJ53onCxmU5Qo2mIPII6TgpcQb8jdBbsW35UzlVqMLWdBwGUASd9PC5xAk417fNe1IFlY31Z97jDkLn0XJ5swsjUfbecfVFENB2a2gq2UDO6292HHReGZKRJN0nhqu5%2BYEjUqueQpahhCyQKIWtyw8HPt9FZYIkvcGy3XRaGAkQY%2Bes1KyBc2ucZ0NU2xQjm8XVnZEhxLKeEk37pYbyFHl7BsedoSvOsf3UxiRpxLkylaD4GxNubRxZYAEDHY%2B1tGmcDFWitD5ZBVPvSPTUTF24qQzV5k%2FEP4uJk7kl81VxLaMLNUqmrinzRh94dCrPS6LGAioOPRYVPWaZpwDbNX5ok%2BIl2gheHwaOASRshIRuM8sPWgJIoOshK7I0EVt26q7d%2Fu5N1UzLuT62c6w8EUSxRWu%2FcmohKlA%3D%3D",
      },
    ],
    description_raw:
      "<p>Please learn the vocab linked below. If you cannot see it, email me: redacted@school.com</p><p>There will be a mini test on this in the first week back!</p>",
  },
  {
    lesson: "9/Sp1",
    subject: "Spanish",
    teacher: "Miss P Reed",
    homework_type: "Homework",
    id: 10314104,
    title: "Spanish Holiday Hmwk",
    meta_title: "",
    description:
      "Please learn the vocab linked below. If you cannot see it, email me: redacted@school.comThere will be a mini test on this in the first week back!",
    issue_date: "2022-02-08",
    due_date: "2022-02-24",
    completion_time_unit: "minutes",
    completion_time_value: "",
    publish_time: "00:00:00",
    status: {
      id: 236697362,
      state: null,
      mark: null,
      mark_relative: 0,
      ticked: "no",
      allow_attachments: "no",
      first_seen_date: "null",
      last_seen_date: "null",
      attachments: [],
      has_feedback: false,
    },
    validated_links: [],
    validated_attachments: [
      {
        id: 7820592,
        file_name: "Yr 7 Ropa.PNG",
        file: 'https://attachments.classcharts.com/h/186461/ba5110ccdaca332819a194ed62bb88fb_20220208_093911.PNG?GoogleAccessId=attachments-classcharts%40edukey-classcharts.iam.gserviceaccount.com&Expires=1646356881&Signature=jp6l4BbCU5LsqecFbSgkOOo%2F%2BY2N2zN%2FU7It4r3nfmnADY6nWz3zDsNaGvw2XS2EBQ1VoKsav%2FmKlGy5vzlMGg%2Frg3aH1RmwI9Hr%2BpO8Ax5UJJDSD97BiwyH68S3A9WU0n%2FO6ZVfH43B4nWvGfIlOWJTx7UyEyOVVKou%2FrMyjUMoHc6zF7gaaNhi2aAi5pMrj%2B%2B6Ojdpt00wBRR3TQ06tB7ahAciTkMqCl4vGiA8n5LNMP9pjygAwl%2BIt7i6iGfSSt24Ra6Mda35htThi2%2FQsMvUN0QMFoULWWFEQQZfyoMYO7DC1LyCheV%2FWNMzBRjgjMMpmqjxGOjJPWlWHnFQog%3D%3D&response-content-disposition=attachment; filename="Yr+7+Ropa.PNG"',
        validated_file:
          "https://www.classcharts.com/redirect?url=MDU3NzI2ZjY0YjVmODA2MzE1MGY4Y2IxMGQ0Yjk0YTJkMzczZTQ0YTZlYjRlZTA5NmFjNjgxMzcwODY3NzQyOfn93WgSLBfbmha3XyvxzcZBu0up8msXG61Hf8DeafSHl2UxzJGUIugp9R0ZS7A7%2BiNZhgNwmebUEJL7d9Y%2FMc0Mkby0%2BXF5l3qR9CK%2Fek2jSAku9FE9%2BWy1EiEG4%2F7DYlsA%2FGwBi5n4unk9x5qscz%2BEHuin%2FSvXFrconEMj6fB%2FSbjcl7vV8qi4dlf6U5Ht%2BBBBTkESi4HouzzIV3fXhg%2FLBPRcd2w7z1%2F%2FZxpM01CUHYqFvb%2BQ0GiXeE9kq83It%2B82ZRy4ZBs9X08YFUeE7kbdu3UKKrk%2FtcVJuMKx%2B6TcwLrS8Rw6Z0oRAnXyTiSmL4lpr%2Fm1SxheDVEk9KD3%2BUhi7EbRsWQYbOyv5Gcv7t2AyKQUkohA5YYRAKdgbfkKDHY9eWl3pIj9jsAc8%2FMQFOhkIQqLnZ1sEg94Fe3ljpt%2FutPK1nvXJDoBseIlLMFWW8netvJDk1fUi96J0yglYCjjXP2KFM%2FZ%2FdWb016uk7oZwleUOmwVDKBoCf2%2FHDJGIrMvwfHILgqlbFuIGChRnCMB0LLLQmrOprHACIa0%2BESmtwKrOoRrjINlYwHeG6o3fjt3u%2B1CxypoW9S2H%2BARpXXq676uDhHGaUveQy2euutg%2Bm6DT1seDxgXxrLpULu4Sn2erIaf4ojOOQJXYogTnvM4YB0nPzTPcAYEnbC8IaWXkqr%2BEkk6oK4V2LgPh1b9WySCSb0K3RBZYJB8IvEqt4FBxjz%2FoUe91ikCt8zApyBjQ0QW%2FY0UWgaBWnymOkQZTlcHJvThwjeH4baLHrSr7Efji4rWgdfym2YCwOt9JhCjt%2FqqFU1zoGxg0liDUO%2FRUnZ8EQ129qv0RSqrGG1ls3e%2BjjNQ31FQpJQ%2Fm6nq9P9YfUyQz51b3vdNZ9HG3ehvIw%3D%3D",
      },
    ],
    description_raw:
      "<p>Please learn the vocab linked below. If you cannot see it, email me: redacted@school.com</p><p>There will be a mini test on this in the first week back!</p>",
  },
  {
    lesson: "9/Re1",
    subject: "Religious Education",
    teacher: "Mrs S Farrell",
    homework_type: "Homework",
    id: 10219126,
    title: "F is for forgiveness",
    meta_title: "",
    description:
      "Follow the link below and watch the\nvideo. The word document (or pdf if that's easier) has\nquestions for you to answer based on the video. There is also\nan extension research task for you to try if you would like to push\nyourself and earn extra house points but this is optional.",
    issue_date: "2022-02-22",
    due_date: "2022-03-01",
    completion_time_unit: "minutes",
    completion_time_value: "",
    publish_time: "00:00:00",
    status: {
      id: 234470567,
      state: "completed",
      mark: null,
      mark_relative: 0,
      ticked: "no",
      allow_attachments: "yes",
      first_seen_date: "2022-02-28T19:21:42+00:00",
      last_seen_date: "2022-02-28T19:21:42+00:00",
      attachments: [
        {
          id: 11776096,
          file_name: "RE Homework.docx",
          file: "https://attachments.classcharts.com/h/186461/ec74f79b258db17914afea9ce94af638_20220228_192146.docx?GoogleAccessId=attachments-classcharts%40edukey-classcharts.iam.gserviceaccount.com&Expires=1646356881&Signature=KMOcSpIGzHqG0DWXe1bZhCqQXovnoW4dtwuPKRDj6CR7XtLPnuckZkj6tViJazv5rhMK9S6IIgd8qklq1z7ipmB%2Fh4N4poE7TGWLN21V%2FrkHuq8y8b2%2BZGork46y%2BHIP2vR%2Bcdw2RJ%2FA5tBzRQg30GSG8eVCs94OO%2Fq5gHHcl2dhINBjzGTyKwoD%2BHkwyZ2K0T7Lmq0cCxvWFUcPe0suAiPNMpAkGMlN9icO9o6pj9%2FfF585U7qeonWG9MyMc8Xlp%2FlQSmBgROH%2Fx%2FAAkU%2FSARktd0sTpGj%2Bf3xUFhvBmdABYU6L1sUZd6GM4NXf9ns6yk4ouMrbNFDSeO1iw0q9ZA%3D%3D",
          validated_file:
            "https://www.classcharts.com/redirect?url=NDZjNDllY2ExMDRmZjA5ZjFlMmIyN2Q1MzIxMmUxMzdmMGUwNDdmNDJjOGVjNmNiOTQ4MjIxY2VhYWZlZTRhNiSKThMmp0jpOHx4KT2EqT5ziJkvhmwx5EODELVAlmIV%2F%2FNXxym4aV0nxvEiCm%2BW%2FDTbohuPdc9U06ezUtHDVlTR%2BcTXBN1kBAx9ThK6tgYoS8YxRpmMGm2s8skvbDBLX%2FSAUQAx2QmOVs5OqwVdVyhfixt225HgM2cp9ZBKpXjTz4I%2F7brTiabpB9231UFVj%2FbcqQjBfq690T6x4EDo46cmjuaREAP8yRQgLTA%2Bgr7oQZLyL%2B53%2BSd6E%2BpzpPvoSc2jJTx5yEPouLEhA0xp5i%2F4F3ZCJNxTrsoUEsLNzVWJboikAz7QYROkOcXAO16h5hAr8%2Fov192JpvTRoIsOFJrMWwZhB7XDWsB7aSdUlb4lxkkHCHvxZayICM%2FOlDGoAqu1kLFD5yqKksOfe67dE4aHdCaiN85%2FG9CUKYgHm6c6of2a3S%2BlS85WpiaADB%2F3kdZnCw3RzOugcb6%2BnP9uTnemEDhi5w1AIKDalMAeC4o8NaGpxmlgYPrAqh1TAsepYT1leJwgH%2FhaNSa%2Fp%2FIBHzGPk0xcr%2FSSlGhg6dfio3U6UUe8o7RVJdvjDnDA7nkpLCCQxC4NbyYVQiQediks9tZHgV7eqKnt1UOXQAHGPwUy9fV7MW5mlztRfyqLgC%2BfOvRiCqqVMHC0uo4k6gfDKkABkWGXlb7%2Fu8dmWurBeXJF5JIIhFaEj0%2F2m4xsdm8DU1DweKONsVV9QB%2FylmDv5Zk7694BQhxhDoSbsL5gs0Ww4%2F57%2Be%2FtocwMyDSvJg6445C6F%2FNr8jnGcgfr2yBE%2Fq2HPueKhsqxFfgRd3xCQNKv%2FiV64XcBbJaNhPsOJeILQhTVbDXcVbM29vxFML8ywfjaLUQ3cNvKzP4VaA88zRj%2F1nkSsA3HiFv4dlZc3X4POkS6NzDsGrRqV%2FcddXDMO3Y%3D",
          teacher_note: "",
          teacher_homework_attachments: [],
          can_delete: true,
        },
      ],
      has_feedback: false,
    },
    validated_links: [
      {
        link: "https://www.bbc.co.uk/teach/class-clips-video/religious-education-ks3-a-z-of-religion-and-beliefs-f-is-for-forgiveness/zf62pg8",
        validated_link:
          "https://www.classcharts.com/redirect?url=NzQ1N2RlYzdjNjkyMzdlNjBiMDhhN2M4MjU1ZTkzZmQzYzg2ZmY4YmUwMGY3NDg5ODU0OGIwNGUzODRhY2JlNHTeX77r8%2BDxyJZaQcr1SHbsRDqcOphOXM3znCeK9EXhecnoAwr%2BLKJ%2Bp0MqDqE0G3cun8AzY2h7aGbpa%2FBqqkUcB8duFiU18T47b%2BWLwtQD0l0KC8BGPFtpM2eV6ju7FzG2IUUue7bh3BCzlNkCuf4WAyoXoZPNDdYRTcY1GNxLqGn%2BdrmdNF4R08MfjQod3g%3D%3D",
      },
    ],
    validated_attachments: [
      {
        id: 7759752,
        file_name: "Homework 6 - F is for Forgiveness.docx",
        file: 'https://attachments.classcharts.com/h/186461/cc77f39c1bfb435df52055465a006952_20220210_090825.docx?GoogleAccessId=attachments-classcharts%40edukey-classcharts.iam.gserviceaccount.com&Expires=1646356881&Signature=E6gHh4zIcA35RtawoY4q4XR2vnIEW6MFcw2Cv%2BUiSGi8IU9G7e5L%2Bfa%2Bev8TKw5KjWB8rAsPVFL0oMQcYKXYSKUeKd%2BwBTPlih4wwM1qNwQOugD8HZk9EhZpbIeGcod%2FgCz7kc5%2FoecXkneEFaTOAQb6zBY4j08d%2BWM556nbVJ0UKa6OJY9hr0Y3S2VQqcdsG8VZGjgBu1KbWV1lThPfdiKSDGB%2BhhTITjxPDZV%2BCv6tkiL1foDTegmQYrz8813CBBSAsdmOqhqSejBNWQQhfhQdY6lvCiEvdD8McP5pN8TX5DGgwGhxCmUjFLWVIeybXa3aO9i60%2BRmIn55ExsOOA%3D%3D&response-content-disposition=attachment; filename="Homework+6+-+F+is+for+Forgiveness.docx"',
        validated_file:
          "https://www.classcharts.com/redirect?url=ZDMyZTAyNDFkODhkOTdjZDY0NDA3OTIxN2QxZTdhNjA4ZTVkODJiOGI5OTE4ZjlkNzhkZmExMTgxODdhMzNkZHMoEWcypCsMpK90Mx%2FMeQeRwEkF3GUDY9YsKrSIr1DoEaG7daTys75k03Dio%2FwMyQqvrKGdXC3KbkEgf1G%2FDp2GKldRA8hQ5Ofn7mo1Zyxgn9EpG0qszOV%2FcSurLx34gO3neWr2N4KcWqr1Dxjmp95bw39U4bCDjD216bB%2F5IED5thMoDcKabsXg0vrGHTGOVdRxaB%2Bu4eVt6%2Bvs6FTAeGWUM5LlyHjiPALRPzRv%2BZOnAh0SlSXrqa5BEilnx8YLdKN9rCPD%2FkrChoa7iZNJ8as4ojHlqa8DCQUhMJKPkceO8DOx3zbPOTYCtSuXa4P2XSpnGh5k%2BQBq9YM7HpfuxCVRSrNBJitXRpyD3WwlsV%2FQyVww3CY7juaLBPe8iySZLmTIsxNFGqYUsdQ%2FLuHX3zBg09x6vKqEsKXAfsjLuA%2BuXfEMZKEUHBxYpUFvujF4Mz6uL3XhPGKpNfit%2FutNFNi6nmirnDEkkjFAnSW2VWlJZVTPiD0YmtYPDVrWvm3mnhYZ%2FHe3VbqI6lZZlXrjxoaEUZNvH7vJkI%2FPktZ3UgZxungCqNGmGp0hwH6M%2F9Pw4NuSfH51aSVfHqi3PHiA4RHG5KwnTFiuEOQHFbYt%2F05VG%2FlPl3Jke0j6ykLCWjrFIy8hUW9M9K%2Fbq%2Bk7KMucr1nLg59CGDdBA%2FyDa6KavpynMXIGs37PzgUFno6nqjI33MWhxH1JLvDWCinXhBWuqwEJxRSei7S%2FoKqBoBCPJv0TCvZf9n704LWSGK6ZTiOpsjl4A6PjtA1QJJQk4JkPHV%2F6aZBDoI8x4AkuXUgvfRFTqF%2BO5JfQE%2Fa0Xdd9FbcNEg7qFt%2Fe8tXM6Fbb47TmdnFkuNx9ymWymQ1nSGYDKYeDxzP6rtxs5sCekglKQIjV0IvVFukFICEAjIHIgslRWk%3D",
      },
      {
        id: 7759753,
        file_name: "Homework 6 - F is for Forgiveness.pdf",
        file: 'https://attachments.classcharts.com/h/186461/bc3473bacad0904743f226370e232a8c_20220210_090834.pdf?GoogleAccessId=attachments-classcharts%40edukey-classcharts.iam.gserviceaccount.com&Expires=1646356881&Signature=IFU3l69Rs%2FLhE3s6dalKibmMIULQgbJjNzi34yCxZUFbIOrJN69zJ1S1tu9KFXQLgEzJMXzDv9n7D%2FxdYqhyb6nG0IviH%2FkDHzogXmvoRIX6e9eOn3EVQFaVDpfWHxRvu5v4DhSOrEZgnnx9dBWk09DZrn6apb8nUzo4GfRvelpmoFGE%2FsPV4pKScoh0BZtqSPxfcYi3SvIutewAlg6fqlLJuWgZ79XtnkF%2F%2BMeG%2FvMio7SFt5ziE05GplEu2eAB30EDFuuaRGjl2hl28myZ7GHWpIxJvwBjS5mAQfYmODftn0kFGYES4yp2iX09Gi%2FPDDqf4D0HexdCjo2X%2F7RCbw%3D%3D&response-content-disposition=attachment; filename="Homework+6+-+F+is+for+Forgiveness.pdf"',
        validated_file:
          "https://www.classcharts.com/redirect?url=OGU5MGJkYTU0Y2JhYjM4YTBmODkxZDRkZjQzZDAyMjNhMWQyMzNhNjgwM2QxNTE4NmEwZTM3YzJlMTM3ZjY2NLPKUUUboelIZW7yAs1afqWlIzOVxJSDXdYWEtENzwh%2BZnYAFYywQjJfzXJMgMqv%2Bu2aGDVwpFPm84IH8p57hNRAEO9SRSvoZxyOVEqizKHNvTOW0JEwr%2F206pEh8GthrdzcekWGJAZbfNLEheNV9CYjTqHf65BUWjzuYsGVYSXgzTqYihtdpfIuN8a0pg9%2FMYDtmMKZW3bpacMLF3Q14L7hxxglr%2FahDVlMY4YG%2BEsOi72uqp7MV9C6uGxPwSINwu3kEBUtBqHMiLst0Q9kcuBaefYdhaEGkM56sDmkh3sIMvpy7ksbE6cNT6pcGDb8lZkH629XVqMyVjdB2td5S0Une%2FXcKcC%2FvPyAgHeppzntkGYhc%2FwD0cbP0v0LwDMcfmplM7JRLaLgQhAa6lS1dRqn4DeUxDhHD%2Bvz4kVMUxvb9HdzVTIXvkakLBi1fh5jh9CMtxKahc0wOvTvSgG1BMjL%2BHYHSxGuK7pyGs%2Fh0KVvgG4rnE0QxwQh3FWijjKEbn3e5jzI%2FKmxdjLa1Fxl19VQxZX%2B3E7y%2BRzxCOuVorZ01tmEInZpus9TLDvHq6SxK3Lsp18BwqwumXquUxxpNJj9oQJ2bE2wWq0j369Y7%2B0YSdVCnz19bXS0fQSI9O7LnTkCPaVQRzzjvo%2BImqYB5xWOF6bj8KPQbjpPXShv4CfeTnGw%2BW9gdCaRHPlk1HKHoIhHclW769hF5cu%2FVSTa%2FNIIM7%2Byd4ddrItp1P376w6dHxVG7gxztH2563%2Bq7Y5KK5FwIi7lSDgQY4lQdhZka%2FvDZ7I%2BTI5PUIp8lnzkmOuqCGhnLehLbqjeOvDUdOAeW%2BIA0jIUXvdjykG9hZRImWLEVtuytap1WQkdXMuMvEJE3aQKtLN1YNnvm4vpk6gTLdXH51JBSdIz2AMcFcEGJ4I%3D",
      },
    ],
    description_raw:
      '\n\n\n\n\n<span style="font-size: 13px;">Follow the link below and watch the\nvideo.&nbsp; The word document (or pdf if that\'s easier) has&nbsp;\nquestions for you to answer based on the video.&nbsp; There is also\nan extension research task for you to try if you would like to push\nyourself and earn extra house points but this is optional.</span>\n\n',
  },
  {
    lesson: "9/Sp1",
    subject: "Spanish",
    teacher: "Miss P Reed",
    homework_type: "Homework",
    id: 10328473,
    title: "Spanish Quizlet link",
    meta_title: "",
    description:
      "https://quizlet.com/571994626/y7-me-gusta-llevar-clothes-flash-cards/",
    issue_date: "2022-02-24",
    due_date: "2022-03-02",
    completion_time_unit: "minutes",
    completion_time_value: "",
    publish_time: "00:00:00",
    status: {
      id: 237040013,
      state: null,
      mark: null,
      mark_relative: 0,
      ticked: "no",
      allow_attachments: "no",
      first_seen_date: "2022-02-25T07:20:29+00:00",
      last_seen_date: "2022-02-25T07:20:29+00:00",
      attachments: [],
      has_feedback: false,
    },
    validated_links: [
      {
        link: "https://quizlet.com/571994626/y7-me-gusta-llevar-clothes-flash-cards/",
        validated_link:
          "https://www.classcharts.com/redirect?url=NDQ2MDNmODIyMjA4Yzg2YjViNDEwOGVlMTdkZjlmNWM2NzMzZjU5YjYxMmMwYWQ1MDYxNzY1OTUyZDdiNTc1N9cdC1bUXI9uCYsM5rpV5Pequk5905UIYqnliW%2B0Nbu%2FyChV80o5bEsGkl7pQz3jR7J2nGXh9DcifiHoj31Dbn%2FJi7kqzVxGrRV4KMaYPuczYyRTjNV2EgaVCKBtRO2bsw%3D%3D",
      },
    ],
    validated_attachments: [],
    description_raw:
      "https://quizlet.com/571994626/y7-me-gusta-llevar-clothes-flash-cards/\n\n\n\n\n\n",
  },
  {
    lesson: "9A/En",
    subject: "English",
    teacher: "Mr C Peacock",
    homework_type: "Homework",
    id: 10330227,
    title: "Bedrock",
    meta_title: "",
    description:
      "Complete 2 blocks of learning on Bedrock. Library and After School homework club is available.",
    issue_date: "2022-02-24",
    due_date: "2022-03-04",
    completion_time_unit: "minutes",
    completion_time_value: "30",
    publish_time: "00:00:00",
    status: {
      id: 237081865,
      state: null,
      mark: null,
      mark_relative: 0,
      ticked: "no",
      allow_attachments: "no",
      first_seen_date: "null",
      last_seen_date: "null",
      attachments: [],
      has_feedback: false,
    },
    validated_links: [],
    validated_attachments: [],
    description_raw:
      "Complete 2 blocks of learning on Bedrock. Library and After School homework club is available.\n\n\n\n\n\n",
  },
  {
    lesson: "9/Sp1",
    subject: "Spanish",
    teacher: "Miss P Reed",
    homework_type: "Homework",
    id: 10355356,
    title: "Spanish Homework Sheet",
    meta_title: "",
    description:
      "Complete the sheet you were given in class. It is also linked\nbelow. Any problems come and find me before the deadline in F10.",
    issue_date: "2022-03-03",
    due_date: "2022-03-10",
    completion_time_unit: "minutes",
    completion_time_value: "",
    publish_time: "00:00:00",
    status: {
      id: 237688791,
      state: null,
      mark: null,
      mark_relative: 0,
      ticked: "no",
      allow_attachments: "no",
      first_seen_date: "2022-03-03T07:13:54+00:00",
      last_seen_date: "2022-03-03T07:13:54+00:00",
      attachments: [],
      has_feedback: false,
    },
    validated_links: [],
    validated_attachments: [
      {
        id: 7841056,
        file_name: "Yr 7 homework sheet.PNG",
        file: 'https://attachments.classcharts.com/h/186461/a48e11fe57a3d0d8ddbb4928b240ad55_20220228_121731.PNG?GoogleAccessId=attachments-classcharts%40edukey-classcharts.iam.gserviceaccount.com&Expires=1646356881&Signature=i7gPZfrjamqTYJI6cTzEs%2FrFo9AN0eXIPRc4pIjTOxwGUolekgdytG5T%2Fc4z6KAF%2BNp4R%2Bt6%2BFyMKoACe3UdIrvORxEbIVNGnkm3%2B1Fz7GqXul8%2FgVqBLX1e1JOdC2DZXQY6%2FVdeopsGWOsULY4WnEJQKttdzINn0p0%2BtwdQqIzNIKNh%2FXTY4jcd88l1e%2F2OtoXIZPgjpKshgzo9cKJV6VgDKmeD2%2Fe9cQa%2Bcrx1s9wTTtHqUDqPiWo9sgs%2BS2HZ1ateveuUx8nlEe%2FRFPQei0WPPxbJZGLGvhJUeuxHzODDIeW%2Fs%2FsfYSZ05kBT1iMIz9XG7IqEBTGfsKCG%2BSPMPA%3D%3D&response-content-disposition=attachment; filename="Yr+7+homework+sheet.PNG"',
        validated_file:
          "https://www.classcharts.com/redirect?url=MmMxMzU4ZTU1OWUxMDdkOTU1MWJhN2IxNDU5MTQ1MzE2ZGFjNDI1M2YzOTI3MTk2NjM4ZjRkNzM0MDc4YTBhM6MB2J47r6UvjfC1SHllcN3WBdKO7Nd0JHpaMcreHw7%2FKEjXjwbldBmfyqtlq8Ln2E1JsfMk73823%2FdRHQ6jSYqlJTnm%2BnUxQTSthdCuRdxEagK7S79Cy%2FL%2FZ1Zc2tEjLB7TEvsp%2FRO2oRCjcY84B15mDGycIiTUxlKHdnjclXLOXqc5GPx2cGijytwllCM01zz%2Bj6F5x44u6Q8ByXAHaw%2FxrjsLeIFitElyQ3tTETQDflYJOQQBeR2SaXFlv3yDDzu0uw1diePzuKxsPhJggvuEZ9aER40%2F%2F6zod3fE1%2BFgvaH9usbsnjVR5aPmxxBWM%2FUNLScclCLOQEGHn%2Fc1vW%2BhwVDKvV3MGxWIzp87ZFu%2BcvJbfM0pzqqrzkhmDxdyUZkvtCLm%2FXe4Ur1p0cR6brJnVEFL1SqLipkZ1mcT1GyhqB2nppEeHTvZChnmXdKZg%2F3IUORArahUL42oC%2F%2B3Bksq2zzTDVBqKFxmzX1Tmcf%2FZsh%2FeGq3FkEG4rqyoX6V5cg2VHcHBRkPFBX3Pat7AGy3qt%2Bxmdfn8Gq1SVNQ1TJcYV1SvQxgVJZ5AHzRkKXQuxTMh6lvrqD120FOkx6kgPXZvr%2FAqizlnktJ4OAh1s7PLNyhwie7TSqFNRfBYIVKJdrpECWQXxEmmrfoS4H6k5dFP0PE3woBKpbV4U9C7BcHNvJk4mgqXdPb9MQ4VWatKpeJAO1C16DSyxAsi3PFb347Cy5q2irN4v5F%2F0nz35vRqAcGN6JORMuf6fQrRjr2sTakeQLtHzgsTJmKMeJbTHm0JCTWju2pFboqbS7KthhAQf%2Bg7WMD6uD8i4vwUHbKC5gl%2BFS0JrXgxSkXJb%2BMQNI7pX%2F0cZazCkeCLMQXTSJTNM5DfKCLQrslrLUuJoCf8ZpdnVG2aj1xR4%2Fc%2FRur878%3D",
      },
    ],
    description_raw:
      "\n\n\n\n\nComplete the sheet you were given in class. It is also linked\nbelow. Any problems come and find me before the deadline in F10.\n\n",
  },
  {
    lesson: "9/Mu1",
    subject: "Music",
    teacher: "Mr E Payne",
    homework_type: "Homework",
    id: 10083357,
    title: "music homework",
    meta_title: "",
    description:
      "Create a colourful A3 display poster for the musical elements.This could be in the form a mindmap (like the one we did in class) or you could try an alternative way.Please include the keyword, it's definition and an image or icon to illustrate the element. The elements to include are -PitchTempoDurationDynamicsTimbreSilenceStructureHarmonyArticulationTextureOstinato",
    issue_date: "2022-02-21",
    due_date: "2022-03-28",
    completion_time_unit: "minutes",
    completion_time_value: "60",
    publish_time: "00:00:00",
    status: {
      id: 231247254,
      state: null,
      mark: null,
      mark_relative: 0,
      ticked: "no",
      allow_attachments: "yes",
      first_seen_date: "null",
      last_seen_date: "null",
      attachments: [],
      has_feedback: false,
    },
    validated_links: [],
    validated_attachments: [],
    description_raw:
      "<p>Create a colourful A3 display poster for the musical elements.</p><p><br></p><p>This could be in the form a mindmap (like the one we did in class) or you could try an alternative way.</p><p>Please include the keyword, it's definition and an image or icon to illustrate the element. The elements to include are -&nbsp;</p><p><br></p><p>Pitch</p><p>Tempo</p><p>Duration</p><p>Dynamics</p><p>Timbre</p><p>Silence</p><p>Structure</p><p>Harmony</p><p>Articulation</p><p>Texture</p><p>Ostinato</p><p><br></p><p><br></p><p>\n\n\n\n\n\n</p>",
  },
];

export const detentionInfo = [];

export const behaviourInfo: BehaviourResponse = {
  timeline: [
    {
      positive: 4,
      negative: 0,
      name: "1/31/2022",
      start: "2022-01-31",
      end: "2022-02-06",
    },
    {
      positive: 11,
      negative: 0,
      name: "2/7/2022",
      start: "2022-02-07",
      end: "2022-02-13",
    },
    {
      positive: 0,
      negative: 0,
      name: "2/14/2022",
      start: "2022-02-14",
      end: "2022-02-20",
    },
    {
      positive: 6,
      negative: 0,
      name: "2/21/2022",
      start: "2022-02-21",
      end: "2022-02-27",
    },
    {
      positive: 4,
      negative: 0,
      name: "2/28/2022",
      start: "2022-02-28",
      end: "2022-03-06",
    },
  ],
  positive_reasons: {
    PROUD: 1,
    "Positive conduct out of class": 1,
    "Outstanding piece of work in lesson": 2,
    "Homework completion": 3,
    "Good piece of work in lesson": 4,
    "Good contribution to lesson": 6,
    "Good attitude to lesson": 7,
  },
  negative_reasons: {},
  other_positive: [],
  other_negative: [],
  other_positive_count: [],
  other_negative_count: [],
};

export const awardsInfo: BadgesResponse = [
  {
    id: 815,
    name: "Bronze House Point Award",
    icon: "17.svg",
    colour: "bronze",
    created_date: "2021-08-23T12:33:23+00:00",
    pupil_badges: [],
    icon_url:
      "https://195ec04504ea0272771e-7c2c6dacbab7a2b2d574b53c70c1fe31.ssl.cf3.rackcdn.com/23.2.0/img/eventbadgeicons/bronze/17.svg",
  },
  {
    id: 816,
    name: "Silver House Point Award",
    icon: "17.svg",
    colour: "silver",
    created_date: "2021-08-23T12:34:52+00:00",
    pupil_badges: [],
    icon_url:
      "https://195ec04504ea0272771e-7c2c6dacbab7a2b2d574b53c70c1fe31.ssl.cf3.rackcdn.com/23.2.0/img/eventbadgeicons/silver/17.svg",
  },
  {
    id: 817,
    name: "Gold House Point Award",
    icon: "17.svg",
    colour: "gold",
    created_date: "2021-08-23T12:36:07+00:00",
    pupil_badges: [],
    icon_url:
      "https://195ec04504ea0272771e-7c2c6dacbab7a2b2d574b53c70c1fe31.ssl.cf3.rackcdn.com/23.2.0/img/eventbadgeicons/gold/17.svg",
  },
  {
    id: 818,
    name: "Diamond House Point Award",
    icon: "17.svg",
    colour: "yellow",
    created_date: "2021-08-23T12:37:34+00:00",
    pupil_badges: [],
    icon_url:
      "https://195ec04504ea0272771e-7c2c6dacbab7a2b2d574b53c70c1fe31.ssl.cf3.rackcdn.com/23.2.0/img/eventbadgeicons/yellow/17.svg",
  },
];

export const announcementsInfo = [];

export const activityInfo: ActivityResponse = [
  {
    id: 786580657,
    type: "behaviour",
    polarity: "positive",
    reason: "PROUD",
    score: 1,
    timestamp: "2022-03-01 16:00:00",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9/Re1",
    teacher_name: "Mrs S Farrell",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 784778232,
    type: "behaviour",
    polarity: "positive",
    reason: "Good contribution to lesson",
    score: 1,
    timestamp: "2022-03-01 15:01:44",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/En",
    teacher_name: "Mr C Peacock",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 784483490,
    type: "behaviour",
    polarity: "positive",
    reason: "Homework completion",
    score: 1,
    timestamp: "2022-03-01 13:15:11",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9/Re1",
    teacher_name: "Mrs S Farrell",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 782398454,
    type: "behaviour",
    polarity: "positive",
    reason: "Positive conduct out of class",
    score: 1,
    timestamp: "2022-02-28 09:44:46",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/Ma",
    teacher_name: "Mr S Kaur",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 781894386,
    type: "behaviour",
    polarity: "positive",
    reason: "Good contribution to lesson",
    score: 1,
    timestamp: "2022-02-25 15:05:37",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/En",
    teacher_name: "Mr C Peacock",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 781280044,
    type: "behaviour",
    polarity: "positive",
    reason: "Good attitude to lesson",
    score: 1,
    timestamp: "2022-02-24 11:59:17",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9/Gg1",
    teacher_name: "Mrs A Field",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 780780238,
    type: "behaviour",
    polarity: "positive",
    reason: "Good piece of work in lesson",
    score: 1,
    timestamp: "2022-02-23 15:02:04",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/Ma",
    teacher_name: "Mr S Kaur",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 780779274,
    type: "behaviour",
    polarity: "positive",
    reason: "Good attitude to lesson",
    score: 1,
    timestamp: "2022-02-23 15:01:28",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/Ma",
    teacher_name: "Mr S Kaur",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 780344784,
    type: "behaviour",
    polarity: "positive",
    reason: "Good attitude to lesson",
    score: 1,
    timestamp: "2022-02-22 15:05:16",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/En",
    teacher_name: "Mr C Peacock",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 779935148,
    type: "behaviour",
    polarity: "positive",
    reason: "Good contribution to lesson",
    score: 1,
    timestamp: "2022-02-21 15:03:20",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/En",
    teacher_name: "Mr C Peacock",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 774335517,
    type: "behaviour",
    polarity: "positive",
    reason: "Outstanding piece of work in lesson",
    score: 2,
    timestamp: "2022-02-11 15:22:23",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9/Dr1",
    teacher_name: "Ms M Murphy",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 774258856,
    type: "behaviour",
    polarity: "positive",
    reason: "Good piece of work in lesson",
    score: 1,
    timestamp: "2022-02-11 15:03:28",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/En",
    teacher_name: "Mr C Peacock",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 774255068,
    type: "behaviour",
    polarity: "positive",
    reason: "Good contribution to lesson",
    score: 1,
    timestamp: "2022-02-11 15:02:40",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/En",
    teacher_name: "Mr C Peacock",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 772808284,
    type: "behaviour",
    polarity: "positive",
    reason: "Homework completion",
    score: 1,
    timestamp: "2022-02-10 15:10:24",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/Ma",
    teacher_name: "Miss E Shah",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 772776843,
    type: "behaviour",
    polarity: "positive",
    reason: "Good attitude to lesson",
    score: 1,
    timestamp: "2022-02-10 15:02:47",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9/Sp1",
    teacher_name: "Mr S Kaur",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 772770576,
    type: "behaviour",
    polarity: "positive",
    reason: "Good piece of work in lesson",
    score: 1,
    timestamp: "2022-02-10 15:01:23",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9/Sp1",
    teacher_name: "Mr S Kaur",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 771048488,
    type: "behaviour",
    polarity: "positive",
    reason: "Good attitude to lesson",
    score: 1,
    timestamp: "2022-02-09 13:49:32",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9/Hi1",
    teacher_name: "Ms S Bird",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 769824322,
    type: "behaviour",
    polarity: "positive",
    reason: "Good attitude to lesson",
    score: 1,
    timestamp: "2022-02-08 15:06:02",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/En",
    teacher_name: "Mr C Peacock",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 769495318,
    type: "behaviour",
    polarity: "positive",
    reason: "Homework completion",
    score: 1,
    timestamp: "2022-02-08 13:12:14",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9/Re1",
    teacher_name: "Mrs S Farrell",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 768356197,
    type: "behaviour",
    polarity: "positive",
    reason: "Good attitude to lesson",
    score: 1,
    timestamp: "2022-02-07 15:03:41",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/En",
    teacher_name: "Mr S Kaur",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 765916493,
    type: "behaviour",
    polarity: "positive",
    reason: "Good contribution to lesson",
    score: 1,
    timestamp: "2022-02-04 11:01:23",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "TuN3/Tu",
    teacher_name: "Mrs E Mellor",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 763532785,
    type: "behaviour",
    polarity: "positive",
    reason: "Good piece of work in lesson",
    score: 1,
    timestamp: "2022-02-02 15:07:40",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/Ma",
    teacher_name: "Miss E Shah",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
  {
    id: 761065292,
    type: "behaviour",
    polarity: "positive",
    reason: "Good contribution to lesson",
    score: 1,
    timestamp: "2022-02-01 09:31:45",
    timestamp_custom_time: null,
    style: {
      border_color: null,
      custom_class: null,
    },
    pupil_name: "Louis Kevan",
    lesson_name: "9A/Sc",
    teacher_name: "Mr S Kaur",
    room_name: null,
    note: "null",
    _can_delete: false,
    badges: "",
    detention_date: null,
    detention_time: null,
    detention_location: null,
    detention_type: null,
  },
];

const user: ClassCharts = {
  student: studentInfo,
  lessons: lessonsInfo,
  homework: homeworkInfo,
  detentions: detentionInfo,
  behaviour: behaviourInfo,
  awards: awardsInfo,
  announcements: announcementsInfo,
  activity: activityInfo,
  allTimeBehaviour: behaviourInfo,
  fake: true,
};

export default user;
